version: '3.8'

name: demo
services:
  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:8080'
    environment:
      PORT: 8080
      MEMBERSHIP_SERVICE_HOST: membership:8081
      INVENTORY_SERVICE_HOST: inventory:8082
      PRICING_SERVICE_HOST: pricing:8083
      COUPON_SERVICE_HOST: coupon:8084
      CURRENCY_SERVICE_HOST: nginx:8085
      GEOLOCATION_SERVICE_HOST: geolocation:8086
  membership:
    build:
      context: ./membership
    ports:
      - '8081:8081'
    environment:
      PORT: 8081
  inventory:
    build:
      context: ./inventory
    ports:
      - '8082:8082'
    environment:
      PORT: 8082
      PYTHONPATH: /opt/odigos-demo-inventory/site-packages
      PYTHONDONTWRITEBYTECODE: 1
      PYTHONUNBUFFERED: 1
  pricing:
    build:
      context: ./pricing
    ports:
      - '8083:8083'
    environment:
      HTTP_PORTS: 8083
  coupon:
    build:
      context: ./coupon
    ports:
      - '8084:8084'
    environment:
      PORT: 8084
      MEMBERSHIP_SERVICE_HOST: membership:8081
  currency:
    build:
      context: ./currency
    expose:
      - '9000'
    ports:
      - '9000:9000'
    environment:
      PORT: 9000
      GEOLOCATION_SERVICE_HOST: geolocation:8086
  nginx:
    image: nginx:alpine
    depends_on:
      - currency
    ports:
      - '8085:8085'
    environment:
      PORT: 8085
    command: >
      sh -c "echo '
        server {
          listen 8085;
          server_name localhost;

          location / {
              include fastcgi_params;
              fastcgi_pass currency:9000;
              fastcgi_param SCRIPT_FILENAME /app/index.php;
          }
        }
      ' > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
  geolocation:
    build:
      context: ./geolocation
    ports:
      - '8086:8086'
    environment:
      PORT: 8086
      RAILS_MASTER_KEY: df0300c20246e24d331787f6540a72fa
