name: odigos-demo-inventory
# arch/version set by Docker build args (TARGETARCH, VERSION) in package stage
arch: ${TARGETARCH}
platform: linux
version: ${VERSION}
section: default
priority: extra
maintainer: Odigos
description: |
  Demo Python application for testing Odigos
vendor: Odigos
homepage: https://odigos.io
depends:
- python3
contents:
- src: distribution/systemd.service
  dst: /lib/systemd/system/odigos-demo-inventory.service
- src: ./dist/app
  dst: /opt/odigos-demo-inventory
scripts:
  preinstall: ./distribution/preinstall.sh
  postinstall: ./distribution/postinstall.sh
  preremove: ./distribution/preremove.sh
