#!/usr/bin/env ruby
require "fileutils"

APP_ROOT = File.expand_path("..", __dir__)

def system!(*args)
  system(*args, exception: true)
end

FileUtils.chdir APP_ROOT do
  puts "== Installing dependencies =="
  system("bundle check") || system!("bundle install")

  puts "\n== Preparing database =="
  system! "binaries/rails db:prepare"

  puts "\n== Removing old logs and tempfiles =="
  system! "binaries/rails log:clear tmp:clear"

  unless ARGV.include?("--skip-server")
    puts "\n== Starting development server =="
    STDOUT.flush
    exec "binaries/dev"
  end
end
