apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: inventory
  namespace: default
spec:
  workload:
    kind: Deployment
    name: inventory
    namespace: default
---
apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: coupon
  namespace: default
spec:
  workload:
    kind: Deployment
    name: coupon
    namespace: default
---
apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: currency
  namespace: default
spec:
  workload:
    kind: Deployment
    name: currency
    namespace: default
---
apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: frontend
  namespace: default
spec:
  workload:
    kind: Deployment
    name: frontend
    namespace: default
---
apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: geolocation
  namespace: default
spec:
  workload:
    kind: Deployment
    name: geolocation
    namespace: default
---
apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: membership
  namespace: default
spec:
  workload:
    kind: Deployment
    name: membership
    namespace: default
---
apiVersion: odigos.io/v1alpha1
kind: Source
metadata:
  name: pricing
  namespace: default
spec:
  workload:
    kind: Deployment
    name: pricing
    namespace: default
