apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Include all YAML files in the current directory
resources:
  - deployment.yaml
  - jaeger.yaml
  - instrument-all.yaml
  - jaeger-dest.yaml

# Add common labels to all resources
labels:
  - pairs:
      app.kubernetes.io/part-of: simple-demo
      app.kubernetes.io/managed-by: kustomize

